[package]
name = "deadlift-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.6.0"
diesel = { version = "2.1.6", features = ["sqlite", "r2d2", "uuid", "chrono", "serde_json"] }
diesel_migrations = "2.1.0"
libsqlite3-sys = { version = "0.28.0", features = ["bundled"] }
once_cell = "1.19.0"
serde = "1.0.203"
tokio = { version = "1.37.0", features = ["full"] }
wasmer = "4.3.1"
wasmer-cache = "4.3.1"
actix-multipart = "0.6.1"
futures-util = "0.3.30"
