[package]
name = "multiply_by_five"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
serde_json = "1.0.117"
extism-pdk = "1.2.0"
